# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  use_frameworks!
  inhibit_all_warnings!

def common_pods
  pod 'SwiftLint'
  pod 'Popover'
end

target 'ClassToday' do
  common_pods
end

target 'ClassToday_NonFirebase' do
  common_pods
end
